import donieleAI from "./images/donieleAI.png"
import portfolioUniversityProject from "./images/portfolioUniversityProject.png"
import logo from "./images/logo3.png"
import profileImg from "./images/profileImg.png"
import netflixbydonieleImg from "./images/netflixbydonieleImg.png"
import donieleprof from "./images/donieleprof.png"
import html from "./images/html.png"
import javascript from "./images/javascript.png"
import typescript from "./images/typescript.png"
import react from "./images/react.png"
import nextjs from "./images/nextjs.png"
import css3 from "./images/css3.png"
import csharp from "./images/csharp.png"
import java from "./images/java.png"
import python from "./images/python.png"
import cplus2 from "./images/cplus2.png"
import nodejs from "./images/nodejs.png"
import tailwindcss from "./images/tailwindcss.png"
import supabase from "./images/supabase.png"
import postgresql from "./images/postgresql.png"
import prisma from "./images/prisma.png"
import scss from "./images/scss.png"
import ucgastrobaguiomockup from "./images/ucgastrobaguiomockup.png"
import ucgastroconsultmockup from "./images/ucgastroconsultmockup.png"
import netflixbydonielemockup from "./images/netflixbydonielemockup.png"
import donieleaimockup from "./images/donieleaimockup.png"
import donielemockup from "./images/donielemockup.png"
import git from "./images/git.png"
import github from "./images/github.png"
import vercel from "./images/vercel.png"
import bootstrap from "./images/bootstrap.png"
import firebase from "./images/firebase.png"
import kalilinux from "./images/kalilinux.png"
import edengreenhouse from './images/edengreenhouse.png'
import edensoft from "./images/edensoft.png"
import flutter from "./images/flutter.png"
import dart from "./images/dart.png"

export { donieleAI, portfolioUniversityProject, logo, profileImg, netflixbydonieleImg, donieleprof, 
html, javascript, typescript, react, nextjs, css3, csharp, java, python, cplus2, nodejs, tailwindcss, 
supabase, postgresql, prisma, scss, ucgastrobaguiomockup, ucgastroconsultmockup,
 netflixbydonielemockup, donieleaimockup, donielemockup, git, github, vercel, 
 bootstrap, firebase, kalilinux, edensoft, edengreenhouse, flutter, dart }
